version: '3.8'

services:
  dev:
    image: alpine:latest
    container_name: aicli-dev
    hostname: aicli
    tty: true
    stdin_open: true
    privileged: true  # Required for some Playwright operations
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./workspace:/home/developer/workspace
      - ./config/nvim:/home/developer/.config/nvim
      - ./config/starship.toml:/home/developer/.config/starship.toml
      - ./config/.tmux.conf:/home/developer/.tmux.conf:ro
      - ./config/.init.sh:/home/developer/workspace/.init.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker support
    environment:
      - TERM=xterm-256color
      - ENABLE_SSH=true
      - ENABLE_DISPLAY=true
      - PLAYWRIGHT_BROWSERS_PATH=/home/developer/.cache/playwright
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - EDITOR=nvim
      - VISUAL=nvim
      - PAGER=bat
      - GIT_AUTHOR_NAME=AI CLI Developer
      - GIT_AUTHOR_EMAIL=aicli@dev.local
      - GIT_COMMITTER_NAME=AI CLI Developer
      - GIT_COMMITTER_EMAIL=aicli@dev.local
    networks:
      - aicli-network
    ports:
      - "2222:22"  # SSH access only

networks:
  aicli-network:
    driver: bridge

