version: '3.8'

services:
  dev:
    image: alpine:latest
    container_name: aicli-dev
    hostname: aicli
    tty: true
    stdin_open: true
    privileged: true  # Required for some Playwright operations
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./workspace:/home/developer/workspace
      - ./config/nvim:/home/developer/.config/nvim
      - ./config/starship.toml:/home/developer/.config/starship.toml
      - ./config/.tmux.conf:/home/developer/.tmux.conf:ro
      - ./config/.init.sh:/home/developer/workspace/.init.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker support
      - aicli-home:/home/developer  # Persist home directory
    environment:
      - TERM=xterm-256color
      - ENABLE_SSH=true
      - ENABLE_DISPLAY=true
      - PLAYWRIGHT_BROWSERS_PATH=/home/developer/.cache/playwright
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - EDITOR=nvim
      - VISUAL=nvim
      - PAGER=bat
      - GIT_AUTHOR_NAME=AI CLI Developer
      - GIT_AUTHOR_EMAIL=aicli@dev.local
      - GIT_COMMITTER_NAME=AI CLI Developer
      - GIT_COMMITTER_EMAIL=aicli@dev.local
    networks:
      - aicli-network
    ports:
      - "2222:22"  # SSH access on port 2222

  caddy:
    image: caddy:alpine
    container_name: aicli-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - aicli-network

networks:
  aicli-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  aicli-home:  # Persist developer home directory